apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: flask-app
  labels:
    app: mysql 
spec:
  clusterIP: None
  selector:
    app: mysql
  ports:
  - port: 3306
    name: db
    targetPort: mysql-container

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: flask-app
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql
  replicas: 3
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8
        ports:
        - containerPort: 3306
          name: mysql-container
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
        env: 
          - name: "MYSQL_USER"
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: db-user
          - name: "MYSQL_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: mysql-password
          - name: "MYSQL_DATABASE"
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: database
          - name: "MYSQL_ROOT_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: mysql-root-password 
  
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      storageClassName: standard
      accessModes: 
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
